### ISSUE TITLE
Bintray brownouts highlight missing maven packages

### ISSUE THREAD

**Issue by jonnii** [tersesystems/terse-logback#123]
**Describe the bug**
During today's scheduled bintray brown out our builds started failing as the following maven coordinates could not resolve:

```
com.tersesystems.logback:logback-structured-config:0.16.1
```

The brownouts are a precursor to the eventual [shutdown of bintray and jcenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). The fix is to start publishing to maven central.

**Comment by wsargent** [comment]
Working on it today, I may need to set up a new publishing key as I've lost the secret key to the bintray one...

**Comment by wsargent** [comment]
```
com.tersesystems.logback:logback-structured-config:0.16.2
```

published to Maven Central.

**Comment by jonnii** [comment]
Thanks for the quick turn around! Can confirm it all works great. 👯
